# Generated by Django 3.2.23 on 2023-12-16 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=2500, null=True)),
                ('health_insurance', models.CharField(blank=True, max_length=2500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_text', models.CharField(blank=True, max_length=2500, null=True)),
                ('date_prescribed', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientCaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.CharField(blank=True, max_length=2500, null=True)),
                ('diagnosis', models.CharField(blank=True, max_length=2500, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=2500, null=True)),
                ('sugar', models.CharField(blank=True, max_length=2500, null=True)),
                ('weight', models.CharField(blank=True, max_length=2500, null=True)),
                ('height', models.CharField(blank=True, max_length=2500, null=True)),
                ('is_diabetic', models.CharField(blank=True, max_length=2500, null=True)),
                ('is_hyper_tension', models.CharField(blank=True, max_length=2500, null=True)),
                ('treatment_plan', models.CharField(blank=True, max_length=2500, null=True)),
                ('major_disease1', models.CharField(blank=True, max_length=2500, null=True)),
                ('major_disease2', models.CharField(blank=True, max_length=2500, null=True)),
                ('major_disease3', models.CharField(blank=True, max_length=2500, null=True)),
                ('major_disease4', models.CharField(blank=True, max_length=2500, null=True)),
                ('major_disease5', models.CharField(blank=True, max_length=2500, null=True)),
                ('any_desription', models.CharField(blank=True, max_length=2500, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(blank=True, max_length=2500, null=True)),
                ('medicine_type', models.CharField(blank=True, max_length=2500, null=True)),
                ('medicine_formula', models.CharField(blank=True, max_length=2500, null=True)),
                ('instruction', models.CharField(blank=True, max_length=2500, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='Lab_examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(blank=True, max_length=2500, null=True)),
                ('test_type', models.CharField(blank=True, max_length=2500, null=True)),
                ('report', models.FileField(blank=True, upload_to='Test_Reports')),
                ('instruction', models.CharField(blank=True, max_length=2500, null=True)),
                ('test_fee', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.prescription')),
            ],
        ),
    ]
