# Generated by Django 3.2.23 on 2023-12-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20231217_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
