# Generated by Django 3.2.23 on 2023-12-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_patient_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
        migrations.AddField(
            model_name='patient',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
    ]
