# Generated by Django 3.2.23 on 2024-03-12 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_medicines_medicine_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_perameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perameter_name', models.CharField(blank=True, max_length=2500, null=True, verbose_name='Test Name')),
                ('ref_range', models.CharField(blank=True, max_length=2500, null=True, verbose_name='Ref. Range')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Test Type')),
                ('test_fee', models.IntegerField(blank=True, null=True, verbose_name='Fee')),
                ('related_perameters', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.test_perameters', verbose_name='Related Perameters')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(blank=True, max_length=2500, null=True, verbose_name='Test Type')),
                ('perameter_name', models.CharField(blank=True, max_length=2500, null=True, verbose_name='Test Name')),
                ('results', models.CharField(blank=True, max_length=2500, null=True, verbose_name='Results')),
                ('ref_range', models.CharField(blank=True, max_length=2500, null=True, verbose_name='Ref. Range')),
                ('date', models.DateTimeField(auto_now=True)),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.prescription')),
            ],
        ),
    ]
