# Generated by Django 3.2.23 on 2024-03-13 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_test_test_perameters_testtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testtype',
            name='related_perameters',
        ),
        migrations.AddField(
            model_name='testtype',
            name='related_perameters',
            field=models.ManyToManyField(blank=True, null=True, to='patient.test_perameters', verbose_name='Related Perameters'),
        ),
    ]
