# Generated by Django 3.2.23 on 2024-03-13 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_auto_20240313_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab_examination',
            name='test_type_id',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
    ]
