# Generated by Django 3.2.23 on 2024-01-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharamacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='billingCity',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='billingCountry',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='billingName',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='billingPostcode',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
